# Generated by Django 2.2 on 2019-04-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='link',
            field=models.TextField(max_length=255),
            preserve_default=False,
        ),
    ]
