# Generated by Django 2.2 on 2019-04-12 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='link',
            new_name='alink',
        ),
    ]
