# Generated by Django 2.2 on 2019-04-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20190413_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='alink',
        ),
        migrations.AddField(
            model_name='job',
            name='too',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
